### ISSUE TITLE
Doesn't boot simulators with Xcode 9

### ISSUE THREAD

**Issue by keesvandieren** [multi-os-engine/moe-ios-simulator-launcher#2]
When using Xcode 9, simulators will not start.  Simulator starts, but it won't boot.

In the log, this warning appears: 2017-09-28 21:40:24.819 simlauncher[42761:1650748] WARNING: Bundle is not present at path: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/CoreSimulator

CoreSimulator.framework seems to have moved to: /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator

**Comment by kisg** [comment]
Fixed on the moe-master branch.
